# Numa Avatar MVP 配置文件模板

backend:
  url: "http://localhost:7301"
  api_token: ""

git:
  username: ""
  email: ""

avatar:
  id: "avatar_mvp_001"
  name: "Developer Avatar MVP"
  workspace: "./workspace"
  topic_name: "tasks"
  log_dir: "./logs"

llm:
  api_key: ""
  model: "gpt-4"
  temperature: 0.7

polling:
  interval: 5