# Numa Avatar MVP 本地配置文件

backend:
  url: "http://localhost:7301"
  api_token: "your_api_token_here"

git:
  username: "Your Name"
  email: "your.email@example.com"

avatar:
  id: "avatar_mvp_001"
  name: "Developer Avatar MVP"
  workspace: "./workspace"
  topic_name: "tasks"
  log_dir: "./logs"

llm:
  api_key: "your_openai_api_key_here"
  model: "gpt-4"
  temperature: 0.7

polling:
  interval: 5