"""add application_id to solutions and development_tasks

Revision ID: 004_add_application_id_to_solutions_and_tasks
Revises: 003_add_solutions_and_questions
Create Date: 2025-08-03 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004_add_application_id_to_solutions_and_tasks'
down_revision = '003_add_solutions_and_questions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_solutions_application_id', 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_development_tasks_requirement_id', 'requirements', ['requirement_id'], ['id'])
        batch_op.create_foreign_key('fk_development_tasks_application_id', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_development_tasks_application_id', type_='foreignkey')
        batch_op.drop_constraint('fk_development_tasks_requirement_id', type_='foreignkey')
        batch_op.drop_column('application_id')
        batch_op.drop_column('requirement_id')

    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solutions_application_id', type_='foreignkey')
        batch_op.drop_column('application_id')
    # ### end Alembic commands ###