"""add assigned_to to development_tasks

Revision ID: 005_add_assigned_to_to_development_tasks
Revises: 004_add_application_id_to_solutions_and_tasks
Create Date: 2025-08-03 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005_add_assigned_to_to_development_tasks'
down_revision = '004_add_application_id_to_solutions_and_tasks'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_development_tasks_assigned_to', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_development_tasks_assigned_to', type_='foreignkey')
        batch_op.drop_column('assigned_to')
    # ### end Alembic commands ###