"""add started_at and completed_at to development_tasks

Revision ID: 006_add_started_at_and_completed_at_to_development_tasks
Revises: 005_add_assigned_to_to_development_tasks
Create Date: 2025-08-03 16:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006_add_started_at_and_completed_at_to_development_tasks'
down_revision = '005_add_assigned_to_to_development_tasks'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
    # ### end Alembic commands ###