"""add code_branch to development_tasks

Revision ID: 007_add_code_branch_to_development_tasks
Revises: 006_add_started_at_and_completed_at_to_development_tasks
Create Date: 2025-08-03 16:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007_add_code_branch_to_development_tasks'
down_revision = '006_add_started_at_and_completed_at_to_development_tasks'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development_tasks', schema=None) as batch_op:
        batch_op.drop_column('code_branch')
    # ### end Alembic commands ###